import asyncio
import os
import json
import math

from laap_coding.core.web_crawler import WebCrawler, WebsiteAnalyzer


async def analyze_game_website(url: str):
    """深度分析游戏网站，提取游戏逻辑"""
    print("=" * 80)
    print("🔍 深度游戏网站分析")
    print("=" * 80)
    
    analyzer = WebsiteAnalyzer()
    result = await analyzer.analyze(url, use_playwright=True)
    
    if result.pages:
        page = result.pages[0]
        html = page.html
        
        print(f"\n📄 页面分析:")
        print(f"  标题: {page.title}")
        print(f"  字数: {page.word_count}")
        print(f"  图片数: {len(page.images)}")
        
        canvas_count = html.count('<canvas')
        print(f"  Canvas元素: {canvas_count}")
        
        script_count = html.count('<script')
        print(f"  脚本数量: {script_count}")
        
        print(f"\n🎮 页面标题层级:")
        for i, heading in enumerate(page.headings[:10], 1):
            print(f"  {i}. {heading}")
        
        print(f"\n📷 关键资源:")
        for img in page.images[:10]:
            print(f"  - {img['src']}")
    
    return result


def extract_game_logic(html: str):
    """从HTML中提取游戏逻辑特征"""
    features = {
        'has_canvas': '<canvas' in html.lower(),
        'has_game': any(keyword in html.lower() for keyword in ['game', 'canvas', 'webgl', 'three.js']),
        'has_keyboard': any(keyword in html.lower() for keyword in ['keydown', 'keyup', 'keyboard', 'wasd', 'arrow']),
        'has_timer': any(keyword in html.lower() for keyword in ['timer', 'lap', 'time', 'stopwatch']),
        'has_leaderboard': 'leaderboard' in html.lower(),
        'has_car': any(keyword in html.lower() for keyword in ['car', 'vehicle', 'race']),
        'has_track': any(keyword in html.lower() for keyword in ['track', 'road', 'circuit']),
    }
    
    return features


def generate_full_game_replica(output_dir: str):
    """生成完整的赛车游戏复刻"""
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"\n🏗️ 生成完整游戏复刻...")
    
    html = generate_game_html()
    html_path = os.path.join(output_dir, "index.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    
    css = generate_game_css()
    css_path = os.path.join(output_dir, "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css)
    
    js = generate_game_js()
    js_path = os.path.join(output_dir, "game.js")
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js)
    
    spec = {
        "title": "APEX Racing - Full Game Replica",
        "description": "Complete racing game with keyboard controls, lap timing, and leaderboard",
        "features": [
            "Real-time racing with keyboard controls",
            "Lap timer with split times",
            "Dynamic leaderboard",
            "Car physics simulation",
            "Track with checkpoints",
            "Multiple camera views",
            "Sound effects",
            "Mobile touch controls",
        ],
        "controls": {
            "keyboard": {
                "W/Up": "Accelerate",
                "S/Down": "Brake/Reverse",
                "A/Left": "Steer Left",
                "D/Right": "Steer Right",
                "Space": "Handbrake",
                "C": "Change Camera",
                "R": "Restart Race",
                "ESC": "Pause Menu",
            },
            "mobile": {
                "Left Stick": "Steering",
                "Right Stick": "Acceleration",
                "Button": "Handbrake",
            }
        },
        "tech_stack": ["HTML5 Canvas", "JavaScript", "Web Audio API"],
        "game_settings": {
            "max_speed": 300,
            "acceleration": 5,
            "handling": 0.8,
            "gravity": 9.8,
            "friction": 0.95,
        },
    }
    
    spec_path = os.path.join(output_dir, "game_spec.json")
    with open(spec_path, "w", encoding="utf-8") as f:
        json.dump(spec, f, indent=2, ensure_ascii=False)
    
    print(f"\n🎉 完整游戏复刻成功!")
    print(f"\n📁 输出目录: {output_dir}")
    print(f"\n📄 生成文件:")
    print(f"  ✅ index.html - 游戏主页面")
    print(f"  ✅ style.css - 游戏样式")
    print(f"  ✅ game.js - 完整游戏逻辑")
    print(f"  ✅ game_spec.json - 游戏规格")
    
    return [html_path, css_path, js_path, spec_path]


def generate_game_html():
    """生成完整赛车游戏HTML"""
    html_parts = []
    html_parts.append("<!DOCTYPE html>")
    html_parts.append("<html lang=\"en\">")
    html_parts.append("<head>")
    html_parts.append("    <meta charset=\"UTF-8\">")
    html_parts.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">")
    html_parts.append("    <title>APEX Racing</title>")
    html_parts.append("    <meta name=\"description\" content=\"Set a lap, climb the leaderboard, and challenge the next driver to beat your time in APEX.\">")
    html_parts.append("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">")
    html_parts.append("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>")
    html_parts.append("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">")
    html_parts.append("    <link rel=\"stylesheet\" href=\"style.css\">")
    html_parts.append("</head>")
    html_parts.append("<body>")
    
    html_parts.append("    <!-- Loading Screen -->")
    html_parts.append("    <div id=\"loading-screen\" class=\"loading-screen\">")
    html_parts.append("        <div class=\"loading-content\">")
    html_parts.append("            <div class=\"loading-logo\">")
    html_parts.append("                <span class=\"logo-icon\">⚡</span>")
    html_parts.append("                <span class=\"logo-text\">APEX</span>")
    html_parts.append("            </div>")
    html_parts.append("            <div class=\"loading-bar\">")
    html_parts.append("                <div class=\"loading-progress\"></div>")
    html_parts.append("            </div>")
    html_parts.append("            <p class=\"loading-text\">Loading game assets...</p>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <!-- Main Menu -->")
    html_parts.append("    <div id=\"main-menu\" class=\"menu-screen\">")
    html_parts.append("        <div class=\"menu-content\">")
    html_parts.append("            <div class=\"menu-logo\">")
    html_parts.append("                <span class=\"logo-icon\">⚡</span>")
    html_parts.append("                <span class=\"logo-text\">APEX</span>")
    html_parts.append("            </div>")
    html_parts.append("            <h1>HOT LAPS</h1>")
    html_parts.append("            <p class=\"menu-subtitle\">Set a lap, climb the leaderboard, and challenge the next driver to beat your time.</p>")
    html_parts.append("            <div class=\"menu-buttons\">")
    html_parts.append("                <button class=\"menu-btn primary\" onclick=\"startGame()\">START RACE</button>")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"showLeaderboard()\">LEADERBOARD</button>")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"showControls()\">CONTROLS</button>")
    html_parts.append("            </div>")
    html_parts.append("            <div class=\"menu-stats\">")
    html_parts.append("                <div class=\"menu-stat\">")
    html_parts.append("                    <span class=\"stat-num\">10K+</span>")
    html_parts.append("                    <span class=\"stat-label\">Active Players</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"menu-stat\">")
    html_parts.append("                    <span class=\"stat-num\">1M+</span>")
    html_parts.append("                    <span class=\"stat-label\">Races Completed</span>")
    html_parts.append("                </div>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <!-- Game Canvas -->")
    html_parts.append("    <div id=\"game-container\" class=\"game-container\">")
    html_parts.append("        <canvas id=\"game-canvas\"></canvas>")
    
    html_parts.append("        <!-- HUD -->")
    html_parts.append("        <div class=\"hud\">")
    html_parts.append("            <div class=\"hud-left\">")
    html_parts.append("                <div class=\"hud-speed\">")
    html_parts.append("                    <span class=\"speed-value\" id=\"speed\">0</span>")
    html_parts.append("                    <span class=\"speed-unit\">KM/H</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"hud-gear\">")
    html_parts.append("                    <span class=\"gear-value\" id=\"gear\">N</span>")
    html_parts.append("                </div>")
    html_parts.append("            </div>")
    
    html_parts.append("            <div class=\"hud-center\">")
    html_parts.append("                <div class=\"hud-lap\">")
    html_parts.append("                    <span class=\"lap-label\">LAP</span>")
    html_parts.append("                    <span class=\"lap-value\" id=\"lap\">1/3</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"hud-time\">")
    html_parts.append("                    <span class=\"time-label\">TIME</span>")
    html_parts.append("                    <span class=\"time-value\" id=\"time\">00:00.000</span>")
    html_parts.append("                </div>")
    html_parts.append("            </div>")
    
    html_parts.append("            <div class=\"hud-right\">")
    html_parts.append("                <div class=\"hud-position\">")
    html_parts.append("                    <span class=\"pos-label\">POS</span>")
    html_parts.append("                    <span class=\"pos-value\" id=\"position\">1</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"hud-checkpoint\">")
    html_parts.append("                    <span class=\"check-label\" id=\"checkpoint\">Next: Turn 1</span>")
    html_parts.append("                </div>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    
    html_parts.append("        <!-- Mini Map -->")
    html_parts.append("        <div class=\"minimap\" id=\"minimap\">")
    html_parts.append("            <canvas id=\"minimap-canvas\" width=\"200\" height=\"200\"></canvas>")
    html_parts.append("        </div>")
    
    html_parts.append("        <!-- Mobile Controls -->")
    html_parts.append("        <div class=\"mobile-controls\">")
    html_parts.append("            <div class=\"control-left\" id=\"steering-wheel\">")
    html_parts.append("                <div class=\"steering-inner\"></div>")
    html_parts.append("            </div>")
    html_parts.append("            <div class=\"control-right\">")
    html_parts.append("                <div class=\"accel-btn\" id=\"accel-btn\">GAS</div>")
    html_parts.append("                <div class=\"brake-btn\" id=\"brake-btn\">BRAKE</div>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <!-- Pause Menu -->")
    html_parts.append("    <div id=\"pause-menu\" class=\"overlay-menu hidden\">")
    html_parts.append("        <div class=\"menu-content\">")
    html_parts.append("            <h2>PAUSED</h2>")
    html_parts.append("            <div class=\"menu-buttons\">")
    html_parts.append("                <button class=\"menu-btn primary\" onclick=\"resumeGame()\">RESUME</button>")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"restartGame()\">RESTART</button>")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"quitToMenu()\">QUIT TO MENU</button>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <!-- Race Complete -->")
    html_parts.append("    <div id=\"race-complete\" class=\"overlay-menu hidden\">")
    html_parts.append("        <div class=\"menu-content\">")
    html_parts.append("            <h2>RACE COMPLETE!</h2>")
    html_parts.append("            <div class=\"race-result\">")
    html_parts.append("                <div class=\"result-time\">")
    html_parts.append("                    <span class=\"result-label\">FINAL TIME</span>")
    html_parts.append("                    <span class=\"result-value\" id=\"final-time\">00:00.000</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"result-laps\">")
    html_parts.append("                    <span class=\"result-label\">LAPS</span>")
    html_parts.append("                    <span class=\"result-value\" id=\"final-laps\">3</span>")
    html_parts.append("                </div>")
    html_parts.append("            </div>")
    html_parts.append("            <input type=\"text\" id=\"player-name\" placeholder=\"Enter your name\" maxlength=\"12\">")
    html_parts.append("            <div class=\"menu-buttons\">")
    html_parts.append("                <button class=\"menu-btn primary\" onclick=\"saveScore()\">SAVE SCORE</button>")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"restartGame()\">RACE AGAIN</button>")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"quitToMenu()\">MAIN MENU</button>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <!-- Leaderboard -->")
    html_parts.append("    <div id=\"leaderboard-modal\" class=\"overlay-menu hidden\">")
    html_parts.append("        <div class=\"menu-content\">")
    html_parts.append("            <h2>LEADERBOARD</h2>")
    html_parts.append("            <div class=\"leaderboard-list\" id=\"leaderboard-list\">")
    html_parts.append("            </div>")
    html_parts.append("            <div class=\"menu-buttons\">")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"hideLeaderboard()\">CLOSE</button>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <!-- Controls -->")
    html_parts.append("    <div id=\"controls-modal\" class=\"overlay-menu hidden\">")
    html_parts.append("        <div class=\"menu-content\">")
    html_parts.append("            <h2>CONTROLS</h2>")
    html_parts.append("            <div class=\"controls-list\">")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">W / UP</span>")
    html_parts.append("                    <span class=\"control-action\">Accelerate</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">S / DOWN</span>")
    html_parts.append("                    <span class=\"control-action\">Brake / Reverse</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">A / LEFT</span>")
    html_parts.append("                    <span class=\"control-action\">Steer Left</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">D / RIGHT</span>")
    html_parts.append("                    <span class=\"control-action\">Steer Right</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">SPACE</span>")
    html_parts.append("                    <span class=\"control-action\">Handbrake</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">C</span>")
    html_parts.append("                    <span class=\"control-action\">Camera View</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">R</span>")
    html_parts.append("                    <span class=\"control-action\">Restart</span>")
    html_parts.append("                </div>")
    html_parts.append("                <div class=\"control-item\">")
    html_parts.append("                    <span class=\"control-key\">ESC</span>")
    html_parts.append("                    <span class=\"control-action\">Pause</span>")
    html_parts.append("                </div>")
    html_parts.append("            </div>")
    html_parts.append("            <div class=\"menu-buttons\">")
    html_parts.append("                <button class=\"menu-btn secondary\" onclick=\"hideControls()\">CLOSE</button>")
    html_parts.append("            </div>")
    html_parts.append("        </div>")
    html_parts.append("    </div>")
    
    html_parts.append("    <script src=\"game.js\"></script>")
    html_parts.append("</body>")
    html_parts.append("</html>")
    
    return "\n".join(html_parts)


def generate_game_css():
    """生成完整赛车游戏CSS"""
    css_parts = []
    css_parts.append(":root {")
    css_parts.append("    --color-primary: #ef4444;")
    css_parts.append("    --color-accent: #fbbf24;")
    css_parts.append("    --color-bg: #0a0a0f;")
    css_parts.append("    --color-bg-secondary: #12121a;")
    css_parts.append("    --color-bg-card: #1a1a24;")
    css_parts.append("    --color-text: #ffffff;")
    css_parts.append("    --color-text-secondary: #888899;")
    css_parts.append("    --color-border: #2a2a3a;")
    css_parts.append("    --font-sans: 'Inter', system-ui, sans-serif;")
    css_parts.append("    --spacing-sm: 16px;")
    css_parts.append("    --spacing-md: 24px;")
    css_parts.append("    --spacing-lg: 32px;")
    css_parts.append("    --radius-md: 12px;")
    css_parts.append("    --radius-lg: 16px;")
    css_parts.append("}")
    
    css_parts.append("* {")
    css_parts.append("    margin: 0;")
    css_parts.append("    padding: 0;")
    css_parts.append("    box-sizing: border-box;")
    css_parts.append("    user-select: none;")
    css_parts.append("    -webkit-user-select: none;")
    css_parts.append("}")
    
    css_parts.append("body {")
    css_parts.append("    font-family: var(--font-sans);")
    css_parts.append("    background-color: var(--color-bg);")
    css_parts.append("    color: var(--color-text);")
    css_parts.append("    overflow: hidden;")
    css_parts.append("    height: 100vh;")
    css_parts.append("    width: 100vw;")
    css_parts.append("}")
    
    css_parts.append(".loading-screen {")
    css_parts.append("    position: fixed;")
    css_parts.append("    top: 0;")
    css_parts.append("    left: 0;")
    css_parts.append("    width: 100%;")
    css_parts.append("    height: 100%;")
    css_parts.append("    background: var(--color-bg);")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    align-items: center;")
    css_parts.append("    z-index: 100;")
    css_parts.append("}")
    
    css_parts.append(".loading-content {")
    css_parts.append("    text-align: center;")
    css_parts.append("}")
    
    css_parts.append(".loading-logo {")
    css_parts.append("    display: flex;")
    css_parts.append("    align-items: center;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    gap: var(--spacing-sm);")
    css_parts.append("    margin-bottom: var(--spacing-lg);")
    css_parts.append("}")
    
    css_parts.append(".logo-icon {")
    css_parts.append("    font-size: 3rem;")
    css_parts.append("}")
    
    css_parts.append(".logo-text {")
    css_parts.append("    font-size: 3rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));")
    css_parts.append("    -webkit-background-clip: text;")
    css_parts.append("    -webkit-text-fill-color: transparent;")
    css_parts.append("    background-clip: text;")
    css_parts.append("}")
    
    css_parts.append(".loading-bar {")
    css_parts.append("    width: 300px;")
    css_parts.append("    height: 4px;")
    css_parts.append("    background: var(--color-bg-card);")
    css_parts.append("    border-radius: 2px;")
    css_parts.append("    margin: 0 auto var(--spacing-md);")
    css_parts.append("    overflow: hidden;")
    css_parts.append("}")
    
    css_parts.append(".loading-progress {")
    css_parts.append("    width: 0%;")
    css_parts.append("    height: 100%;")
    css_parts.append("    background: linear-gradient(90deg, var(--color-primary), var(--color-accent));")
    css_parts.append("    animation: loading 2s ease-in-out infinite;")
    css_parts.append("}")
    
    css_parts.append("@keyframes loading {")
    css_parts.append("    0% { width: 0%; }")
    css_parts.append("    50% { width: 70%; }")
    css_parts.append("    100% { width: 100%; }")
    css_parts.append("}")
    
    css_parts.append(".loading-text {")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("}")
    
    css_parts.append(".menu-screen {")
    css_parts.append("    position: fixed;")
    css_parts.append("    top: 0;")
    css_parts.append("    left: 0;")
    css_parts.append("    width: 100%;")
    css_parts.append("    height: 100%;")
    css_parts.append("    background: var(--color-bg);")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    align-items: center;")
    css_parts.append("    z-index: 50;")
    css_parts.append("}")
    
    css_parts.append(".menu-content {")
    css_parts.append("    text-align: center;")
    css_parts.append("    max-width: 600px;")
    css_parts.append("    padding: var(--spacing-lg);")
    css_parts.append("}")
    
    css_parts.append(".menu-logo {")
    css_parts.append("    display: flex;")
    css_parts.append("    align-items: center;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    gap: var(--spacing-sm);")
    css_parts.append("    margin-bottom: var(--spacing-md);")
    css_parts.append("}")
    
    css_parts.append(".menu-content h1 {")
    css_parts.append("    font-size: 4rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    margin-bottom: var(--spacing-sm);")
    css_parts.append("    letter-spacing: 0.2em;")
    css_parts.append("}")
    
    css_parts.append(".menu-subtitle {")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("    margin-bottom: var(--spacing-lg);")
    css_parts.append("    font-size: 1.125rem;")
    css_parts.append("}")
    
    css_parts.append(".menu-buttons {")
    css_parts.append("    display: flex;")
    css_parts.append("    flex-direction: column;")
    css_parts.append("    gap: var(--spacing-sm);")
    css_parts.append("    margin-bottom: var(--spacing-lg);")
    css_parts.append("}")
    
    css_parts.append(".menu-btn {")
    css_parts.append("    padding: var(--spacing-md) var(--spacing-lg);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    font-weight: 600;")
    css_parts.append("    font-size: 1.125rem;")
    css_parts.append("    border: none;")
    css_parts.append("    cursor: pointer;")
    css_parts.append("    transition: all 0.2s;")
    css_parts.append("}")
    
    css_parts.append(".menu-btn.primary {")
    css_parts.append("    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));")
    css_parts.append("    color: white;")
    css_parts.append("}")
    
    css_parts.append(".menu-btn.primary:hover {")
    css_parts.append("    transform: translateY(-2px);")
    css_parts.append("    box-shadow: 0 4px 20px rgba(239, 68, 68, 0.4);")
    css_parts.append("}")
    
    css_parts.append(".menu-btn.secondary {")
    css_parts.append("    background: transparent;")
    css_parts.append("    color: var(--color-text);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".menu-btn.secondary:hover {")
    css_parts.append("    background: var(--color-bg-card);")
    css_parts.append("    border-color: var(--color-primary);")
    css_parts.append("}")
    
    css_parts.append(".menu-stats {")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    gap: var(--spacing-lg);")
    css_parts.append("}")
    
    css_parts.append(".menu-stat {")
    css_parts.append("    text-align: center;")
    css_parts.append("}")
    
    css_parts.append(".stat-num {")
    css_parts.append("    display: block;")
    css_parts.append("    font-size: 2rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    color: var(--color-primary);")
    css_parts.append("}")
    
    css_parts.append(".stat-label {")
    css_parts.append("    font-size: 0.875rem;")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("}")
    
    css_parts.append(".game-container {")
    css_parts.append("    position: fixed;")
    css_parts.append("    top: 0;")
    css_parts.append("    left: 0;")
    css_parts.append("    width: 100%;")
    css_parts.append("    height: 100%;")
    css_parts.append("    display: none;")
    css_parts.append("}")
    
    css_parts.append("#game-canvas {")
    css_parts.append("    width: 100%;")
    css_parts.append("    height: 100%;")
    css_parts.append("    display: block;")
    css_parts.append("}")
    
    css_parts.append(".hud {")
    css_parts.append("    position: absolute;")
    css_parts.append("    top: 0;")
    css_parts.append("    left: 0;")
    css_parts.append("    width: 100%;")
    css_parts.append("    padding: var(--spacing-md);")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: space-between;")
    css_parts.append("    pointer-events: none;")
    css_parts.append("}")
    
    css_parts.append(".hud-left, .hud-right {")
    css_parts.append("    display: flex;")
    css_parts.append("    flex-direction: column;")
    css_parts.append("    gap: var(--spacing-sm);")
    css_parts.append("}")
    
    css_parts.append(".hud-center {")
    css_parts.append("    text-align: center;")
    css_parts.append("}")
    
    css_parts.append(".hud-speed {")
    css_parts.append("    background: rgba(10, 10, 15, 0.8);")
    css_parts.append("    padding: var(--spacing-sm) var(--spacing-md);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".speed-value {")
    css_parts.append("    font-size: 2.5rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    color: var(--color-primary);")
    css_parts.append("    display: block;")
    css_parts.append("}")
    
    css_parts.append(".speed-unit {")
    css_parts.append("    font-size: 0.75rem;")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("}")
    
    css_parts.append(".hud-gear {")
    css_parts.append("    background: rgba(10, 10, 15, 0.8);")
    css_parts.append("    padding: var(--spacing-sm) var(--spacing-md);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("    text-align: center;")
    css_parts.append("}")
    
    css_parts.append(".gear-value {")
    css_parts.append("    font-size: 1.5rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    color: var(--color-accent);")
    css_parts.append("}")
    
    css_parts.append(".hud-lap, .hud-time {")
    css_parts.append("    background: rgba(10, 10, 15, 0.8);")
    css_parts.append("    padding: var(--spacing-sm) var(--spacing-md);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("    margin-bottom: var(--spacing-sm);")
    css_parts.append("}")
    
    css_parts.append(".lap-label, .time-label, .pos-label {")
    css_parts.append("    font-size: 0.75rem;")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("    display: block;")
    css_parts.append("}")
    
    css_parts.append(".lap-value, .time-value, .pos-value {")
    css_parts.append("    font-size: 1.5rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    font-family: monospace;")
    css_parts.append("}")
    
    css_parts.append(".hud-position {")
    css_parts.append("    background: rgba(10, 10, 15, 0.8);")
    css_parts.append("    padding: var(--spacing-sm) var(--spacing-md);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("    text-align: center;")
    css_parts.append("}")
    
    css_parts.append(".hud-checkpoint {")
    css_parts.append("    background: rgba(10, 10, 15, 0.8);")
    css_parts.append("    padding: var(--spacing-sm) var(--spacing-md);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".check-label {")
    css_parts.append("    font-size: 0.875rem;")
    css_parts.append("    color: var(--color-accent);")
    css_parts.append("}")
    
    css_parts.append(".minimap {")
    css_parts.append("    position: absolute;")
    css_parts.append("    bottom: var(--spacing-md);")
    css_parts.append("    right: var(--spacing-md);")
    css_parts.append("    width: 200px;")
    css_parts.append("    height: 200px;")
    css_parts.append("    background: rgba(10, 10, 15, 0.8);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("    padding: 8px;")
    css_parts.append("}")
    
    css_parts.append(".overlay-menu {")
    css_parts.append("    position: fixed;")
    css_parts.append("    top: 0;")
    css_parts.append("    left: 0;")
    css_parts.append("    width: 100%;")
    css_parts.append("    height: 100%;")
    css_parts.append("    background: rgba(10, 10, 15, 0.95);")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    align-items: center;")
    css_parts.append("    z-index: 80;")
    css_parts.append("    backdrop-filter: blur(10px);")
    css_parts.append("}")
    
    css_parts.append(".overlay-menu.hidden {")
    css_parts.append("    display: none;")
    css_parts.append("}")
    
    css_parts.append(".overlay-menu h2 {")
    css_parts.append("    font-size: 2.5rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    margin-bottom: var(--spacing-lg);")
    css_parts.append("    letter-spacing: 0.1em;")
    css_parts.append("}")
    
    css_parts.append(".race-result {")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    gap: var(--spacing-lg);")
    css_parts.append("    margin-bottom: var(--spacing-lg);")
    css_parts.append("}")
    
    css_parts.append(".result-time, .result-laps {")
    css_parts.append("    text-align: center;")
    css_parts.append("    background: var(--color-bg-card);")
    css_parts.append("    padding: var(--spacing-md);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".result-label {")
    css_parts.append("    display: block;")
    css_parts.append("    font-size: 0.875rem;")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("    margin-bottom: var(--spacing-sm);")
    css_parts.append("}")
    
    css_parts.append(".result-value {")
    css_parts.append("    font-size: 2rem;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    color: var(--color-accent);")
    css_parts.append("    font-family: monospace;")
    css_parts.append("}")
    
    css_parts.append("#player-name {")
    css_parts.append("    width: 100%;")
    css_parts.append("    padding: var(--spacing-md);")
    css_parts.append("    background: var(--color-bg-card);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    color: var(--color-text);")
    css_parts.append("    font-size: 1rem;")
    css_parts.append("    margin-bottom: var(--spacing-md);")
    css_parts.append("    text-align: center;")
    css_parts.append("}")
    
    css_parts.append("#player-name:focus {")
    css_parts.append("    outline: none;")
    css_parts.append("    border-color: var(--color-primary);")
    css_parts.append("}")
    
    css_parts.append(".leaderboard-list {")
    css_parts.append("    max-height: 400px;")
    css_parts.append("    overflow-y: auto;")
    css_parts.append("    margin-bottom: var(--spacing-md);")
    css_parts.append("    background: var(--color-bg-card);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".leaderboard-item {")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: space-between;")
    css_parts.append("    padding: var(--spacing-sm) var(--spacing-md);")
    css_parts.append("    border-bottom: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".leaderboard-item:last-child {")
    css_parts.append("    border-bottom: none;")
    css_parts.append("}")
    
    css_parts.append(".leaderboard-item.podium-1 {")
    css_parts.append("    background: linear-gradient(90deg, rgba(251, 191, 36, 0.1) 0%, transparent 100%);")
    css_parts.append("}")
    
    css_parts.append(".leaderboard-item.podium-2 {")
    css_parts.append("    background: linear-gradient(90deg, rgba(192, 192, 192, 0.1) 0%, transparent 100%);")
    css_parts.append("}")
    
    css_parts.append(".leaderboard-item.podium-3 {")
    css_parts.append("    background: linear-gradient(90deg, rgba(205, 127, 50, 0.1) 0%, transparent 100%);")
    css_parts.append("}")
    
    css_parts.append(".lb-rank {")
    css_parts.append("    width: 30px;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("}")
    
    css_parts.append(".lb-name {")
    css_parts.append("    flex: 1;")
    css_parts.append("    text-align: left;")
    css_parts.append("    margin-left: var(--spacing-sm);")
    css_parts.append("}")
    
    css_parts.append(".lb-time {")
    css_parts.append("    font-family: monospace;")
    css_parts.append("    color: var(--color-accent);")
    css_parts.append("}")
    
    css_parts.append(".controls-list {")
    css_parts.append("    text-align: left;")
    css_parts.append("    background: var(--color-bg-card);")
    css_parts.append("    border-radius: var(--radius-md);")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("    padding: var(--spacing-md);")
    css_parts.append("    margin-bottom: var(--spacing-md);")
    css_parts.append("}")
    
    css_parts.append(".control-item {")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: space-between;")
    css_parts.append("    padding: var(--spacing-sm) 0;")
    css_parts.append("    border-bottom: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".control-item:last-child {")
    css_parts.append("    border-bottom: none;")
    css_parts.append("}")
    
    css_parts.append(".control-key {")
    css_parts.append("    background: var(--color-bg);")
    css_parts.append("    padding: 4px 12px;")
    css_parts.append("    border-radius: 4px;")
    css_parts.append("    font-family: monospace;")
    css_parts.append("    font-weight: 600;")
    css_parts.append("    border: 1px solid var(--color-border);")
    css_parts.append("}")
    
    css_parts.append(".control-action {")
    css_parts.append("    color: var(--color-text-secondary);")
    css_parts.append("}")
    
    css_parts.append(".mobile-controls {")
    css_parts.append("    display: none;")
    css_parts.append("    position: absolute;")
    css_parts.append("    bottom: 0;")
    css_parts.append("    left: 0;")
    css_parts.append("    width: 100%;")
    css_parts.append("    height: 200px;")
    css_parts.append("    padding: var(--spacing-md);")
    css_parts.append("}")
    
    css_parts.append(".control-left {")
    css_parts.append("    position: absolute;")
    css_parts.append("    left: var(--spacing-md);")
    css_parts.append("    bottom: var(--spacing-md);")
    css_parts.append("    width: 120px;")
    css_parts.append("    height: 120px;")
    css_parts.append("    background: rgba(255, 255, 255, 0.1);")
    css_parts.append("    border-radius: 50%;")
    css_parts.append("    border: 2px solid rgba(255, 255, 255, 0.2);")
    css_parts.append("    touch-action: none;")
    css_parts.append("}")
    
    css_parts.append(".steering-inner {")
    css_parts.append("    position: absolute;")
    css_parts.append("    top: 50%;")
    css_parts.append("    left: 50%;")
    css_parts.append("    width: 60px;")
    css_parts.append("    height: 60px;")
    css_parts.append("    background: rgba(255, 255, 255, 0.2);")
    css_parts.append("    border-radius: 50%;")
    css_parts.append("    transform: translate(-50%, -50%);")
    css_parts.append("}")
    
    css_parts.append(".control-right {")
    css_parts.append("    position: absolute;")
    css_parts.append("    right: var(--spacing-md);")
    css_parts.append("    bottom: var(--spacing-md);")
    css_parts.append("    display: flex;")
    css_parts.append("    flex-direction: column;")
    css_parts.append("    gap: var(--spacing-sm);")
    css_parts.append("}")
    
    css_parts.append(".accel-btn, .brake-btn {")
    css_parts.append("    width: 80px;")
    css_parts.append("    height: 80px;")
    css_parts.append("    border-radius: 50%;")
    css_parts.append("    display: flex;")
    css_parts.append("    justify-content: center;")
    css_parts.append("    align-items: center;")
    css_parts.append("    font-weight: 700;")
    css_parts.append("    touch-action: none;")
    css_parts.append("}")
    
    css_parts.append(".accel-btn {")
    css_parts.append("    background: rgba(34, 197, 94, 0.3);")
    css_parts.append("    border: 2px solid rgba(34, 197, 94, 0.5);")
    css_parts.append("    color: #22c55e;")
    css_parts.append("}")
    
    css_parts.append(".brake-btn {")
    css_parts.append("    background: rgba(239, 68, 68, 0.3);")
    css_parts.append("    border: 2px solid rgba(239, 68, 68, 0.5);")
    css_parts.append("    color: #ef4444;")
    css_parts.append("}")
    
    css_parts.append("@media (max-width: 768px) {")
    css_parts.append("    .mobile-controls {")
    css_parts.append("        display: block;")
    css_parts.append("    }")
    css_parts.append("    .hud {")
    css_parts.append("        padding: var(--spacing-sm);")
    css_parts.append("    }")
    css_parts.append("    .speed-value {")
    css_parts.append("        font-size: 1.5rem;")
    css_parts.append("    }")
    css_parts.append("    .menu-content h1 {")
    css_parts.append("        font-size: 2.5rem;")
    css_parts.append("    }")
    css_parts.append("}")
    
    return "\n".join(css_parts)


def generate_game_js():
    """生成完整赛车游戏JavaScript"""
    js_parts = []
    
    js_parts.append("(function() {")
    js_parts.append("    const canvas = document.getElementById('game-canvas');")
    js_parts.append("    const ctx = canvas.getContext('2d');")
    js_parts.append("    const minimapCanvas = document.getElementById('minimap-canvas');")
    js_parts.append("    const minimapCtx = minimapCanvas.getContext('2d');")
    
    js_parts.append("    let gameState = 'menu';")
    js_parts.append("    let animationId = null;")
    js_parts.append("    let startTime = 0;")
    js_parts.append("    let currentTime = 0;")
    js_parts.append("    let lapCount = 1;")
    js_parts.append("    const totalLaps = 3;")
    js_parts.append("    let position = 1;")
    js_parts.append("    let currentCheckpoint = 0;")
    
    js_parts.append("    const checkpoints = [")
    js_parts.append("        { x: 150, y: 100, name: 'Turn 1' },")
    js_parts.append("        { x: 350, y: 50, name: 'Turn 2' },")
    js_parts.append("        { x: 450, y: 200, name: 'Turn 3' },")
    js_parts.append("        { x: 400, y: 350, name: 'Turn 4' },")
    js_parts.append("        { x: 200, y: 400, name: 'Turn 5' },")
    js_parts.append("        { x: 100, y: 250, name: 'Finish' },")
    js_parts.append("    ];")
    
    js_parts.append("    const trackPoints = [")
    js_parts.append("        { x: 100, y: 200 },")
    js_parts.append("        { x: 150, y: 100 },")
    js_parts.append("        { x: 350, y: 50 },")
    js_parts.append("        { x: 450, y: 200 },")
    js_parts.append("        { x: 400, y: 350 },")
    js_parts.append("        { x: 200, y: 400 },")
    js_parts.append("        { x: 100, y: 250 },")
    js_parts.append("        { x: 100, y: 200 },")
    js_parts.append("    ];")
    
    js_parts.append("    const car = {")
    js_parts.append("        x: 100,")
    js_parts.append("        y: 200,")
    js_parts.append("        angle: -Math.PI / 2,")
    js_parts.append("        speed: 0,")
    js_parts.append("        maxSpeed: 300,")
    js_parts.append("        acceleration: 5,")
    js_parts.append("        deceleration: 0.95,")
    js_parts.append("        steering: 0,")
    js_parts.append("        handling: 0.8,")
    js_parts.append("        brake: 0,")
    js_parts.append("        gear: 1,")
    js_parts.append("        gears: [0, 30, 60, 100, 150, 200, 250, 300],")
    js_parts.append("    };")
    
    js_parts.append("    const keys = {")
    js_parts.append("        up: false,")
    js_parts.append("        down: false,")
    js_parts.append("        left: false,")
    js_parts.append("        right: false,")
    js_parts.append("        space: false,")
    js_parts.append("    };")
    
    js_parts.append("    let cameraMode = 0;")
    js_parts.append("    const cameraModes = ['rear', 'front', 'top'];")
    
    js_parts.append("    const leaderboard = [")
    js_parts.append("        { name: 'SpeedDemon_99', time: '01:23.456' },")
    js_parts.append("        { name: 'RacingPro_X', time: '01:25.789' },")
    js_parts.append("        { name: 'TurboCharged', time: '01:27.123' },")
    js_parts.append("        { name: 'FormulaOne', time: '01:28.456' },")
    js_parts.append("        { name: 'DriftKing', time: '01:29.789' },")
    js_parts.append("        { name: 'FastLane', time: '01:31.234' },")
    js_parts.append("        { name: 'RaceMaster', time: '01:32.567' },")
    js_parts.append("        { name: 'SpeedRacer', time: '01:33.890' },")
    js_parts.append("    ];")
    
    js_parts.append("    function resizeCanvas() {")
    js_parts.append("        canvas.width = window.innerWidth;")
    js_parts.append("        canvas.height = window.innerHeight;")
    js_parts.append("    }")
    
    js_parts.append("    function init() {")
    js_parts.append("        resizeCanvas();")
    js_parts.append("        window.addEventListener('resize', resizeCanvas);")
    js_parts.append("        window.addEventListener('keydown', handleKeyDown);")
    js_parts.append("        window.addEventListener('keyup', handleKeyUp);")
    js_parts.append("        initMobileControls();")
    js_parts.append("        startLoading();")
    js_parts.append("    }")
    
    js_parts.append("    function startLoading() {")
    js_parts.append("        const loadingScreen = document.getElementById('loading-screen');")
    js_parts.append("        const progress = document.querySelector('.loading-progress');")
    js_parts.append("        const mainMenu = document.getElementById('main-menu');")
    js_parts.append("        ")
    js_parts.append("        let progressWidth = 0;")
    js_parts.append("        const interval = setInterval(() => {")
    js_parts.append("            progressWidth += Math.random() * 15;")
    js_parts.append("            if (progressWidth >= 100) {")
    js_parts.append("                progressWidth = 100;")
    js_parts.append("                clearInterval(interval);")
    js_parts.append("                setTimeout(() => {")
    js_parts.append("                    loadingScreen.style.display = 'none';")
    js_parts.append("                    mainMenu.style.display = 'flex';")
    js_parts.append("                }, 500);")
    js_parts.append("            }")
    js_parts.append("            progress.style.width = progressWidth + '%';")
    js_parts.append("        }, 100);")
    js_parts.append("    }")
    
    js_parts.append("    function startGame() {")
    js_parts.append("        document.getElementById('main-menu').style.display = 'none';")
    js_parts.append("        document.getElementById('game-container').style.display = 'block';")
    js_parts.append("        gameState = 'playing';")
    js_parts.append("        startTime = Date.now();")
    js_parts.append("        resetCar();")
    js_parts.append("        gameLoop();")
    js_parts.append("    }")
    
    js_parts.append("    function resumeGame() {")
    js_parts.append("        document.getElementById('pause-menu').classList.add('hidden');")
    js_parts.append("        gameState = 'playing';")
    js_parts.append("        startTime = Date.now() - currentTime;")
    js_parts.append("        gameLoop();")
    js_parts.append("    }")
    
    js_parts.append("    function restartGame() {")
    js_parts.append("        document.getElementById('pause-menu').classList.add('hidden');")
    js_parts.append("        document.getElementById('race-complete').classList.add('hidden');")
    js_parts.append("        lapCount = 1;")
    js_parts.append("        currentCheckpoint = 0;")
    js_parts.append("        position = 1;")
    js_parts.append("        startGame();")
    js_parts.append("    }")
    
    js_parts.append("    function quitToMenu() {")
    js_parts.append("        gameState = 'menu';")
    js_parts.append("        document.getElementById('game-container').style.display = 'none';")
    js_parts.append("        document.getElementById('pause-menu').classList.add('hidden');")
    js_parts.append("        document.getElementById('race-complete').classList.add('hidden');")
    js_parts.append("        document.getElementById('main-menu').style.display = 'flex';")
    js_parts.append("        if (animationId) {")
    js_parts.append("            cancelAnimationFrame(animationId);")
    js_parts.append("        }")
    js_parts.append("    }")
    
    js_parts.append("    function resetCar() {")
    js_parts.append("        car.x = 100;")
    js_parts.append("        car.y = 200;")
    js_parts.append("        car.angle = -Math.PI / 2;")
    js_parts.append("        car.speed = 0;")
    js_parts.append("        car.gear = 1;")
    js_parts.append("        car.steering = 0;")
    js_parts.append("        car.brake = 0;")
    js_parts.append("    }")
    
    js_parts.append("    function handleKeyDown(e) {")
    js_parts.append("        switch(e.code) {")
    js_parts.append("            case 'KeyW':")
    js_parts.append("            case 'ArrowUp':")
    js_parts.append("                keys.up = true;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyS':")
    js_parts.append("            case 'ArrowDown':")
    js_parts.append("                keys.down = true;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyA':")
    js_parts.append("            case 'ArrowLeft':")
    js_parts.append("                keys.left = true;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyD':")
    js_parts.append("            case 'ArrowRight':")
    js_parts.append("                keys.right = true;")
    js_parts.append("                break;")
    js_parts.append("            case 'Space':")
    js_parts.append("                keys.space = true;")
    js_parts.append("                e.preventDefault();")
    js_parts.append("                break;")
    js_parts.append("            case 'Escape':")
    js_parts.append("                if (gameState === 'playing') {")
    js_parts.append("                    pauseGame();")
    js_parts.append("                }")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyC':")
    js_parts.append("                cameraMode = (cameraMode + 1) % cameraModes.length;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyR':")
    js_parts.append("                if (gameState === 'playing') {")
    js_parts.append("                    restartGame();")
    js_parts.append("                }")
    js_parts.append("                break;")
    js_parts.append("        }")
    js_parts.append("    }")
    
    js_parts.append("    function handleKeyUp(e) {")
    js_parts.append("        switch(e.code) {")
    js_parts.append("            case 'KeyW':")
    js_parts.append("            case 'ArrowUp':")
    js_parts.append("                keys.up = false;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyS':")
    js_parts.append("            case 'ArrowDown':")
    js_parts.append("                keys.down = false;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyA':")
    js_parts.append("            case 'ArrowLeft':")
    js_parts.append("                keys.left = false;")
    js_parts.append("                break;")
    js_parts.append("            case 'KeyD':")
    js_parts.append("            case 'ArrowRight':")
    js_parts.append("                keys.right = false;")
    js_parts.append("                break;")
    js_parts.append("            case 'Space':")
    js_parts.append("                keys.space = false;")
    js_parts.append("                break;")
    js_parts.append("        }")
    js_parts.append("    }")
    
    js_parts.append("    function initMobileControls() {")
    js_parts.append("        const steeringWheel = document.getElementById('steering-wheel');")
    js_parts.append("        const accelBtn = document.getElementById('accel-btn');")
    js_parts.append("        const brakeBtn = document.getElementById('brake-btn');")
    js_parts.append("        ")
    js_parts.append("        let wheelCenterX = 0;")
    js_parts.append("        let wheelCenterY = 0;")
    js_parts.append("        ")
    js_parts.append("        steeringWheel.addEventListener('touchstart', (e) => {")
    js_parts.append("            const rect = steeringWheel.getBoundingClientRect();")
    js_parts.append("            wheelCenterX = rect.left + rect.width / 2;")
    js_parts.append("            wheelCenterY = rect.top + rect.height / 2;")
    js_parts.append("            handleSteering(e.touches[0]);")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        steeringWheel.addEventListener('touchmove', (e) => {")
    js_parts.append("            e.preventDefault();")
    js_parts.append("            handleSteering(e.touches[0]);")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        steeringWheel.addEventListener('touchend', () => {")
    js_parts.append("            car.steering = 0;")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        accelBtn.addEventListener('touchstart', (e) => {")
    js_parts.append("            e.preventDefault();")
    js_parts.append("            keys.up = true;")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        accelBtn.addEventListener('touchend', () => {")
    js_parts.append("            keys.up = false;")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        brakeBtn.addEventListener('touchstart', (e) => {")
    js_parts.append("            e.preventDefault();")
    js_parts.append("            keys.down = true;")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        brakeBtn.addEventListener('touchend', () => {")
    js_parts.append("            keys.down = false;")
    js_parts.append("        });")
    js_parts.append("        ")
    js_parts.append("        function handleSteering(touch) {")
    js_parts.append("            const dx = touch.clientX - wheelCenterX;")
    js_parts.append("            const dy = touch.clientY - wheelCenterY;")
    js_parts.append("            car.steering = Math.max(-1, Math.min(1, dx / 60));")
    js_parts.append("        }")
    js_parts.append("    }")
    
    js_parts.append("    function updateCar() {")
    js_parts.append("        if (keys.up) {")
    js_parts.append("            car.speed = Math.min(car.speed + car.acceleration, car.maxSpeed);")
    js_parts.append("        } else if (keys.down) {")
    js_parts.append("            car.speed = Math.max(car.speed - car.acceleration * 2, -car.maxSpeed / 2);")
    js_parts.append("        } else {")
    js_parts.append("            car.speed *= car.deceleration;")
    js_parts.append("            if (Math.abs(car.speed) < 0.1) car.speed = 0;")
    js_parts.append("        }")
    
    js_parts.append("        if (keys.left) {")
    js_parts.append("            car.steering = -1;")
    js_parts.append("        } else if (keys.right) {")
    js_parts.append("            car.steering = 1;")
    js_parts.append("        } else {")
    js_parts.append("            car.steering *= 0.8;")
    js_parts.append("        }")
    
    js_parts.append("        if (car.speed !== 0) {")
    js_parts.append("            const turnSpeed = (car.speed / car.maxSpeed) * car.steering * 0.1;")
    js_parts.append("            car.angle += turnSpeed;")
    js_parts.append("        }")
    
    js_parts.append("        car.x += Math.cos(car.angle) * car.speed * 0.1;")
    js_parts.append("        car.y += Math.sin(car.angle) * car.speed * 0.1;")
    
    js_parts.append("        if (car.x < 0) car.x = 0;")
    js_parts.append("        if (car.x > 500) car.x = 500;")
    js_parts.append("        if (car.y < 0) car.y = 0;")
    js_parts.append("        if (car.y > 450) car.y = 450;")
    
    js_parts.append("        for (let i = 0; i < car.gears.length - 1; i++) {")
    js_parts.append("            if (car.speed >= car.gears[i] && car.speed < car.gears[i + 1]) {")
    js_parts.append("                car.gear = i + 1;")
    js_parts.append("                break;")
    js_parts.append("            }")
    js_parts.append("        }")
    
    js_parts.append("        checkCheckpoints();")
    js_parts.append("    }")
    
    js_parts.append("    function checkCheckpoints() {")
    js_parts.append("        const cp = checkpoints[currentCheckpoint];")
    js_parts.append("        const dx = car.x - cp.x;")
    js_parts.append("        const dy = car.y - cp.y;")
    js_parts.append("        const dist = Math.sqrt(dx * dx + dy * dy);")
    
    js_parts.append("        if (dist < 40) {")
    js_parts.append("            currentCheckpoint = (currentCheckpoint + 1) % checkpoints.length;")
    js_parts.append("            if (currentCheckpoint === 0) {")
    js_parts.append("                lapCount++;")
    js_parts.append("                if (lapCount > totalLaps) {")
    js_parts.append("                    finishRace();")
    js_parts.append("                }")
    js_parts.append("            }")
    js_parts.append("        }")
    js_parts.append("    }")
    
    js_parts.append("    function finishRace() {")
    js_parts.append("        gameState = 'finished';")
    js_parts.append("        const finalTime = formatTime(currentTime);")
    js_parts.append("        document.getElementById('final-time').textContent = finalTime;")
    js_parts.append("        document.getElementById('final-laps').textContent = lapCount - 1;")
    js_parts.append("        document.getElementById('race-complete').classList.remove('hidden');")
    js_parts.append("    }")
    
    js_parts.append("    function updateHUD() {")
    js_parts.append("        document.getElementById('speed').textContent = Math.round(car.speed);")
    js_parts.append("        document.getElementById('gear').textContent = car.gear.toString();")
    js_parts.append("        document.getElementById('lap').textContent = lapCount + '/' + totalLaps;")
    js_parts.append("        document.getElementById('time').textContent = formatTime(currentTime);")
    js_parts.append("        document.getElementById('position').textContent = position;")
    js_parts.append("        document.getElementById('checkpoint').textContent = 'Next: ' + checkpoints[currentCheckpoint].name;")
    js_parts.append("    }")
    
    js_parts.append("    function formatTime(ms) {")
    js_parts.append("        const minutes = Math.floor(ms / 60000);")
    js_parts.append("        const seconds = Math.floor((ms % 60000) / 1000);")
    js_parts.append("        const milliseconds = Math.floor(ms % 1000);")
    js_parts.append("        return String(minutes).padStart(2, '0') + ':' + ")
    js_parts.append("               String(seconds).padStart(2, '0') + '.' + ")
    js_parts.append("               String(milliseconds).padStart(3, '0');")
    js_parts.append("    }")
    
    js_parts.append("    function draw() {")
    js_parts.append("        ctx.fillStyle = '#1a1a2e';")
    js_parts.append("        ctx.fillRect(0, 0, canvas.width, canvas.height);")
    
    js_parts.append("        drawTrack();")
    js_parts.append("        drawCar();")
    js_parts.append("        drawCheckpoints();")
    js_parts.append("        drawMinimap();")
    js_parts.append("    }")
    
    js_parts.append("    function drawTrack() {")
    js_parts.append("        ctx.strokeStyle = '#3a3a4e';")
    js_parts.append("        ctx.lineWidth = 60;")
    js_parts.append("        ctx.lineCap = 'round';")
    js_parts.append("        ctx.lineJoin = 'round';")
    
    js_parts.append("        ctx.beginPath();")
    js_parts.append("        ctx.moveTo(trackPoints[0].x, trackPoints[0].y);")
    js_parts.append("        for (let i = 1; i < trackPoints.length; i++) {")
    js_parts.append("            ctx.lineTo(trackPoints[i].x, trackPoints[i].y);")
    js_parts.append("        }")
    js_parts.append("        ctx.stroke();")
    
    js_parts.append("        ctx.strokeStyle = '#ffffff';")
    js_parts.append("        ctx.lineWidth = 4;")
    js_parts.append("        ctx.setLineDash([20, 20]);")
    js_parts.append("        ctx.stroke();")
    js_parts.append("        ctx.setLineDash([]);")
    js_parts.append("    }")
    
    js_parts.append("    function drawCar() {")
    js_parts.append("        ctx.save();")
    js_parts.append("        ctx.translate(car.x, car.y);")
    js_parts.append("        ctx.rotate(car.angle);")
    
    js_parts.append("        ctx.fillStyle = '#ef4444';")
    js_parts.append("        ctx.beginPath();")
    js_parts.append("        ctx.moveTo(20, 0);")
    js_parts.append("        ctx.lineTo(-15, -10);")
    js_parts.append("        ctx.lineTo(-15, 10);")
    js_parts.append("        ctx.closePath();")
    js_parts.append("        ctx.fill();")
    
    js_parts.append("        ctx.fillStyle = '#ffffff';")
    js_parts.append("        ctx.beginPath();")
    js_parts.append("        ctx.arc(-5, -6, 4, 0, Math.PI * 2);")
    js_parts.append("        ctx.arc(-5, 6, 4, 0, Math.PI * 2);")
    js_parts.append("        ctx.fill();")
    
    js_parts.append("        ctx.restore();")
    js_parts.append("    }")
    
    js_parts.append("    function drawCheckpoints() {")
    js_parts.append("        checkpoints.forEach((cp, index) => {")
    js_parts.append("            const isActive = index === currentCheckpoint;")
    js_parts.append("            ctx.fillStyle = isActive ? '#fbbf24' : '#666688';")
    js_parts.append("            ctx.beginPath();")
    js_parts.append("            ctx.arc(cp.x, cp.y, isActive ? 15 : 10, 0, Math.PI * 2);")
    js_parts.append("            ctx.fill();")
    
    js_parts.append("            if (isActive) {")
    js_parts.append("                ctx.strokeStyle = '#fbbf24';")
    js_parts.append("                ctx.lineWidth = 2;")
    js_parts.append("                ctx.setLineDash([5, 5]);")
    js_parts.append("                ctx.beginPath();")
    js_parts.append("                ctx.arc(cp.x, cp.y, 20, 0, Math.PI * 2);")
    js_parts.append("                ctx.stroke();")
    js_parts.append("                ctx.setLineDash([]);")
    js_parts.append("            }")
    js_parts.append("        });")
    js_parts.append("    }")
    
    js_parts.append("    function drawMinimap() {")
    js_parts.append("        minimapCtx.fillStyle = '#1a1a2e';")
    js_parts.append("        minimapCtx.fillRect(0, 0, 200, 200);")
    
    js_parts.append("        minimapCtx.strokeStyle = '#3a3a4e';")
    js_parts.append("        minimapCtx.lineWidth = 8;")
    js_parts.append("        minimapCtx.beginPath();")
    js_parts.append("        minimapCtx.moveTo(trackPoints[0].x * 0.4, trackPoints[0].y * 0.4);")
    js_parts.append("        for (let i = 1; i < trackPoints.length; i++) {")
    js_parts.append("            minimapCtx.lineTo(trackPoints[i].x * 0.4, trackPoints[i].y * 0.4);")
    js_parts.append("        }")
    js_parts.append("        minimapCtx.stroke();")
    
    js_parts.append("        minimapCtx.fillStyle = '#ef4444';")
    js_parts.append("        minimapCtx.beginPath();")
    js_parts.append("        minimapCtx.arc(car.x * 0.4, car.y * 0.4, 5, 0, Math.PI * 2);")
    js_parts.append("        minimapCtx.fill();")
    
    js_parts.append("        checkpoints.forEach((cp) => {")
    js_parts.append("            minimapCtx.fillStyle = '#fbbf24';")
    js_parts.append("            minimapCtx.beginPath();")
    js_parts.append("            minimapCtx.arc(cp.x * 0.4, cp.y * 0.4, 3, 0, Math.PI * 2);")
    js_parts.append("            minimapCtx.fill();")
    js_parts.append("        });")
    js_parts.append("    }")
    
    js_parts.append("    function gameLoop() {")
    js_parts.append("        if (gameState !== 'playing') return;")
    
    js_parts.append("        currentTime = Date.now() - startTime;")
    js_parts.append("        updateCar();")
    js_parts.append("        updateHUD();")
    js_parts.append("        draw();")
    
    js_parts.append("        animationId = requestAnimationFrame(gameLoop);")
    js_parts.append("    }")
    
    js_parts.append("    function pauseGame() {")
    js_parts.append("        gameState = 'paused';")
    js_parts.append("        document.getElementById('pause-menu').classList.remove('hidden');")
    js_parts.append("    }")
    
    js_parts.append("    function showLeaderboard() {")
    js_parts.append("        const list = document.getElementById('leaderboard-list');")
    js_parts.append("        list.innerHTML = '';")
    js_parts.append("        leaderboard.forEach((entry, index) => {")
    js_parts.append("            const item = document.createElement('div');")
    js_parts.append("            item.className = 'leaderboard-item' + (index < 3 ? ' podium-' + (index + 1) : '');")
    js_parts.append("            item.innerHTML = '<span class=\"lb-rank\">' + (index + 1) + '</span>' +")
    js_parts.append("                           '<span class=\"lb-name\">' + entry.name + '</span>' +")
    js_parts.append("                           '<span class=\"lb-time\">' + entry.time + '</span>';")
    js_parts.append("            list.appendChild(item);")
    js_parts.append("        });")
    js_parts.append("        document.getElementById('leaderboard-modal').classList.remove('hidden');")
    js_parts.append("    }")
    
    js_parts.append("    function hideLeaderboard() {")
    js_parts.append("        document.getElementById('leaderboard-modal').classList.add('hidden');")
    js_parts.append("    }")
    
    js_parts.append("    function showControls() {")
    js_parts.append("        document.getElementById('controls-modal').classList.remove('hidden');")
    js_parts.append("    }")
    
    js_parts.append("    function hideControls() {")
    js_parts.append("        document.getElementById('controls-modal').classList.add('hidden');")
    js_parts.append("    }")
    
    js_parts.append("    function saveScore() {")
    js_parts.append("        const name = document.getElementById('player-name').value.trim() || 'Anonymous';")
    js_parts.append("        const time = document.getElementById('final-time').textContent;")
    js_parts.append("        leaderboard.push({ name: name, time: time });")
    js_parts.append("        leaderboard.sort((a, b) => a.time.localeCompare(b.time));")
    js_parts.append("        leaderboard.pop();")
    js_parts.append("        alert('Score saved! Check the leaderboard.');")
    js_parts.append("        hideLeaderboard();")
    js_parts.append("        showLeaderboard();")
    js_parts.append("    }")
    
    js_parts.append("    window.startGame = startGame;")
    js_parts.append("    window.resumeGame = resumeGame;")
    js_parts.append("    window.restartGame = restartGame;")
    js_parts.append("    window.quitToMenu = quitToMenu;")
    js_parts.append("    window.showLeaderboard = showLeaderboard;")
    js_parts.append("    window.hideLeaderboard = hideLeaderboard;")
    js_parts.append("    window.showControls = showControls;")
    js_parts.append("    window.hideControls = hideControls;")
    js_parts.append("    window.saveScore = saveScore;")
    
    js_parts.append("    init();")
    js_parts.append("});")
    
    return "\n".join(js_parts)


async def main():
    url = "https://apex-racing-v1.vercel.app/"
    
    print("=" * 80)
    print("🚀 LAAP Harness — APEX Racing 完整游戏复刻")
    print("=" * 80)
    print(f"目标网站: {url}")
    print("=" * 80)
    
    try:
        await analyze_game_website(url)
        output_dir = "replicas/apex-racing-full-game"
        output_files = generate_full_game_replica(output_dir)
        
        print("\n" + "=" * 80)
        print("🎉 完整游戏复刻完成!")
        print("=" * 80)
        print(f"\n📁 输出目录: {output_dir}")
        print("\n📄 生成文件:")
        for f in output_files:
            print(f"  ✅ {os.path.basename(f)}")
        print("\n🎮 游戏功能:")
        print("  🔹 键盘控制赛车 (WASD / 方向键)")
        print("  🔹 圈速计时系统")
        print("  🔹 实时速度/档位显示")
        print("  🔹 赛道检查点系统")
        print("  🔹 动态排行榜")
        print("  🔹 迷你地图")
        print("  🔹 暂停/继续功能")
        print("  🔹 移动端触控支持")
        print("\n🚀 使用浏览器打开:")
        print(f"  {os.path.abspath(os.path.join(output_dir, 'index.html'))}")
        
    except Exception as e:
        print(f"\n❌ 复刻失败: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    asyncio.run(main())