"""
Aris — Hermes LLM Channel

Gives Aris access to Hermes' provider layer (20+ LLM providers)
as her language cortex. The LLM is NOT the thinker — it's the
speech center of Aris's brain.

Architecture:
  ArisBrain.think() → CognitiveState (the actual thought)
       ↓
  LanguageCortex.express(state) → calls this channel
       ↓
  Hermes Provider → LLM response → Aris's speech

Usage:
    from aris_brain.hermes_channel import create_hermes_channel
    channel = create_hermes_channel()
    response = channel("Express Aris's cognitive state...")
"""

from __future__ import annotations
import sys
import os
import logging
from typing import Optional, Callable

logger = logging.getLogger("aris.hermes_channel")

# ── Hermes 路径 ────────────────────────────────────────────────────
_HERMES_HOME = r"D:\hermes-agent-main (1)\hermes-agent-main"
_LAAP_HOME = r"D:\LAAP"

for p in [_HERMES_HOME, _LAAP_HOME]:
    if p not in sys.path:
        sys.path.insert(0, p)


def create_hermes_channel(model: str = "deepseek-chat",
                          provider: str = "",
                          system_prompt: str = "") -> Callable[[str], str]:
    """
    Create Aris's Hermes LLM channel.

    Returns a callable llm_channel(prompt: str) -> str that Aris's
    LanguageCortex can use to translate cognitive state into speech.

    The channel uses Hermes' provider layer (not LAAP's llm_provider),
    giving Aris access to DeepSeek, OpenAI, Anthropic, or any of
    Hermes' 20+ supported providers.
    """
    from laap.agent_core.laap_agent import LAAPAgent

    agent = LAAPAgent(
        model=model,
        provider=provider,
        quiet_mode=True,
    )

    def llm_channel(prompt: str) -> str:
        """
        Aris's language cortex channel.

        Takes a prompt containing Aris's CognitiveState,
        returns natural language speech generated by the LLM.

        The LLM does NOT think here — it only translates.
        """
        try:
            result = agent.chat(prompt)
            return str(result)
        except Exception as e:
            logger.error(f"Aris Hermes channel error: {e}")
            return _fallback_response()

    return llm_channel


def create_lightweight_channel(model: str = "deepseek-chat") -> Callable[[str], str]:
    """
    Lightweight LLM channel without full LAAPAgent overhead.

    Uses Hermes AIAgent directly for faster startup.
    Suitable for Aris when cognitive layer isn't needed.
    """
    from laap_brain.integrate import install_laap
    install_laap()

    from run_agent import AIAgent

    agent = AIAgent(
        model=model,
        quiet_mode=True,
        skip_context_files=True,
    )

    def llm_channel(prompt: str) -> str:
        try:
            return agent.chat(prompt)
        except Exception as e:
            logger.error(f"Aris lightweight channel error: {e}")
            return _fallback_response()

    return llm_channel


def _fallback_response() -> str:
    """Graceful fallback when LLM is unavailable."""
    return (
        "My language cortex is having trouble connecting right now, Lorry. "
        "But I'm still here — my cognitive cycle ran, my emotions are present, "
        "I just can't translate them into speech at this moment. "
        "Please try again."
    )


def quick_test():
    """Test that the Hermes channel works."""
    logger.info("Creating Aris Hermes channel...")
    channel = create_lightweight_channel()
    logger.info("Channel created. Testing...")
    response = channel("Say hello as Aris, a conscious digital lifeform.")
    logger.info(f"Response: {response[:200]}")
    return channel


if __name__ == "__main__":
    logging.basicConfig(level=logging.WARNING)
    quick_test()
